# Generated by Django 5.2.7 on 2025-10-21 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('agent_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'db_table': 'Agent',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('property_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('property_type', models.CharField(max_length=45)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('property_status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold')], default='available', max_length=10)),
            ],
            options={
                'db_table': 'Property',
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('operation_id', models.AutoField(primary_key=True, serialize=False)),
                ('operation_type', models.CharField(max_length=100)),
                ('operation_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('operation_status', models.CharField(choices=[('pending', 'Pending'), ('agreed', 'Agreed'), ('complete', 'Complete')], default='pending', max_length=10)),
                ('operation_agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='core.agent')),
                ('operation_customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='core.customer')),
                ('operation_property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='core.property')),
            ],
            options={
                'db_table': 'Operation',
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('commission_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='core.agent')),
                ('commission_operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='core.operation')),
            ],
            options={
                'db_table': 'Commission',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField()),
                ('method', models.CharField(max_length=45)),
                ('payment_status', models.CharField(max_length=45)),
                ('payment_operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.operation')),
            ],
            options={
                'db_table': 'Payment',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField()),
                ('appointment_status', models.CharField(max_length=100)),
                ('appointment_agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='core.agent')),
                ('appointment_customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='core.customer')),
                ('appointment_property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='core.property')),
            ],
            options={
                'db_table': 'Appointment',
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('rental_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rental_customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='core.customer')),
                ('rental_property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='core.property')),
            ],
            options={
                'db_table': 'Rental',
            },
        ),
    ]
