# Generated by Django 5.2.7 on 2025-11-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appointment",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="commission",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="customer",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="operation",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="payment",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="property",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="rental",
            options={"managed": False},
        ),
        migrations.AlterField(
            model_name="agent",
            name="email",
            field=models.EmailField(max_length=75, unique=True),
        ),
        migrations.AlterField(
            model_name="agent",
            name="phone_number",
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
