# Generated by Django 5.2.7 on 2025-11-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="services",
            field=models.ManyToManyField(
                blank=True, db_table="booking_service", to="hotel_management.service"
            ),
        ),
    ]
